### ISSUE TITLE
Variable Buoyancy System (VBS) actuator

### ISSUE THREAD

**Issue by nilsbore** [patrykcieslak/stonefish#4]
**Is your feature request related to a problem? Please describe.**
We have a vehicle with a VBS pumping in and out water. The best way to represent this
in simulation would probably be a block of water with changing proportions (the cylinder
in this example is filled with water when the VBS is pumping in and vice versa).

**Describe the solution you'd like**
I'm not exactly sure, but I'm envisioning something like an actuator with a mass that
can change either its volume or its mass.

**Describe alternatives you've considered**
Again, not really sure. One could just hook into the simulator and apply some kind of force.
That's what we've done before in Gazebo but we would like also the center of gravity to
change since the center of mass is moving when the water volume is extended/decreased.

Any suggestions for short-term solutions would also be very welcome.

**Comment by patrykcieslak** [comment]
I can implement an actuator which will be based on a rigid body, attached to one of the links of the robot, with a variable mass and inertia. Variable volume is also possible if I assume that the actual mesh is not changing, because scaling the mesh in realtime may be too expensive (but it will not work when crossing the surface :/).

I am not sure from your description how is the VBS actually working. It pumps water to a rigid tank or to something like a balloon?

**Comment by nilsbore** [comment]
Just variable mass and inertia would already be useful for us. We have a
cylinder on the vehicle with a piston that pushes out seawater from the
cylinder, or lets it come in. Since it is quite elongated, the center of
mass can actually shift quite a bit. Therefore, a cylinder with variable
length (and constant mass density) would be very useful, since that would
allow us to test pitch control when the VBS is operating. In that model,
one end of the cylinder would stay at a constant position wrt the parent
link while the other end could move.

Den fre 1 nov. 2019 17:00Patryk Cieślak <notifications@github.com> skrev:

**Comment by nilsbore** [comment]
Maybe I should also clarify that the cylinder is mounted inside the pressure hull of the vehicle, so on one side of the piston is just air, and on the other side is seawater coming in from an inlet in the hull that goes to the cylinder.

**Comment by nilsbore** [comment]
@patrykcieslak Do you have time to look at this in the near future or should I give it a try? In that case, could you give me some pointers if I were to implement just the variable mass and inertia option?

**Comment by patrykcieslak** [comment]
Yes I will implement it this week. It is quite complicated because I have to use some functions of Bullet I didn't use before and I need to test if changing the inertia and mass when the simulation is running really works. I was also thinking about how to deal with changing centre of gravity (CG) and came up with one idea. I am thinking that for example when creating the actuator you could pass two meshes which would represent the water volume when the actuator is full and empty. From these meshes I would get centres of gravity, mass, inertia, at the limits of the actuator. The only problem is that maybe the water is completely expelled from the system in the "empty" state? But  then passing a very small volume would be a solution. I would interpolate between these two cases to get the numbers. Of course for a cylinder it would work perfectly, for other shapes no so much, but I guess most often it is something more or less cylindrical. The external shell would be considered rigid and not a part of actuator definition but just represented by part of the vehicle.

I think I will implement the VBS in two stages:
1. Simple version -> generate force acting on the vehicle based on amount of water, taking into account CG and mass 
2. Realistic version -> an actual body changing inertial parameters, attached to the vehicle

The second version will add the effects that the actuator will have on the dynamics of the vehicle, not only on the statics.

Question:
How would you see controlling the actuator? I was thinking there could be something like a flow rate that you control and the actuator automatically computes how much water is in the cylinder, based on the meshes you provide when creating it.

**Comment by nilsbore** [comment]
This plan sounds promising and I think it should be quite flexible if others have other types of VBS systems. One idea would be to extend it further to have a list of meshes, and the system could always interpolate  between the two in the current interval. E.g. if you have a list of meshes `[m_1, m_2, m_3, m_4]` and the current setpoint of the VBS is 50% full, the physics could interpolate between `m_2` and `m_3`, whereas if it's at 20%, it would interpolate between `m_1` and `m_2`. Of course, in our case, we would still only need two endpoints so this is just a suggestion for making it more general.

Answer:
A flow rate sounds good as we want to be able to compute the speed of actuation. I think in our case, we will convert it to the velocity of the piston but that is very easily done, and again, flow rate is more general. Having the actuator take a volume as control input would also be an option, with the flow rate being only a parameter of the actuator. Either way, we need some way of getting the current volume back out to ROS.

**Comment by patrykcieslak** [comment]
I added support for the VBS on Friday. It is the "stage 1" implementation. I also modified stonefish_ros to support it. Look at the parsed Girona500 example to see how it is defined.
Basically you give a list of meshes in arbitrary order, which describe the volume of the liquid in the VBS. The mass, volume and CG are computed automatically and the meshes are sorted by volume. The largest volume is considered the max volume and the smallest the minimum. When preparing the meshes you have to take care to keep the same coordinate system because this coordinate system will be used to attach the actuator to the robot and the computation of the CG position for a specific state of the system is done in reference to this coordinate system. What I mean is that if you have a mesh representing a full tank in form of a cylinder and you put the reference frame in the middle, for the empty state the mesh will not be centred anymore (look at the example meshes). By having a list of meshes you have more control over the interpolation like you suggested. I just realised you don't have to pass the information about a set point associated with every mesh because the set point is directly connected with volume.

**Comment by nilsbore** [comment]
Hey. Very nice, I'm trying it out right now! Seems to be a very sensible way of defining the coordinate system of the different meshes, thanks. For clarification: is it assumed that the meshes has the density of water? It seems to work very well for our vehicle, with the center of mass changing noticeably. Thanks for getting this done so quickly! Closing the issue!
